#!/usr/bin/env python3
"""
Capvid static contract auditor.

Verifies the internal contracts of the repository that a normal compile would
NOT catch (or that fail only at runtime on a device):

  1.  Java package declaration vs. source directory
  2.  every com.saad.capvid.* import resolves to a type declared in this repo
  3.  caption style catalog ids  <->  CaptionOverlayView.CaptionStyleType enum
  4.  StyleFontMap covers every enum value, and every asset it names exists
  5.  ASS family names claimed by StyleFontMap vs. the REAL family name inside
      each bundled font (libass matches on the font's name table, so a
      mismatch silently falls back to DejaVu Sans in the exported video)
  6.  every R.layout / R.id / R.drawable / R.string / R.mipmap / R.style /
      R.color / R.dimen reference resolves to a real resource
  7.  every findViewById(R.id.x) in an Activity resolves in that Activity's layout
  8.  every native method declared in WhisperBridge has a matching JNI symbol
      with the correct mangled name in native-lib.cpp
  9.  manifest <activity> classes exist
 10.  CMakeLists source/include paths exist
 11.  bundled fonts actually referenced by something (dead APK weight)
 12.  FontManager.FONT_FILES vs. what is really in assets/fonts

Exit code is non-zero when any ERROR is found, so this can gate CI.
"""

import os
import re
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JAVA_ROOT = os.path.join(ROOT, "app/src/main/java")
RES_ROOT = os.path.join(ROOT, "app/src/main/res")
ASSETS_ROOT = os.path.join(ROOT, "app/src/main/assets")
CPP_ROOT = os.path.join(ROOT, "app/src/main/cpp")

ERRORS = []
WARNINGS = []


def err(check, msg):
    ERRORS.append((check, msg))


def warn(check, msg):
    WARNINGS.append((check, msg))


def section(title):
    print("\n== %s ==" % title)


# ---------------------------------------------------------------- 1 + 2 -----
def load_java():
    """-> {fqcn: (path, package, src)}, ordered list of paths"""
    files = []
    for dirpath, _dirs, names in os.walk(JAVA_ROOT):
        for n in names:
            if n.endswith(".java"):
                files.append(os.path.join(dirpath, n))
    files.sort()
    infos = {}
    for p in files:
        src = open(p, encoding="utf-8", errors="replace").read()
        m = re.search(r"^\s*package\s+([\w.]+)\s*;", src, re.M)
        pkg = m.group(1) if m else ""
        cls = os.path.basename(p)[:-5]
        infos[pkg + "." + cls] = (p, pkg, src)
    return files, infos


def check_packages(files, infos):
    section("1. package declaration vs source directory")
    bad = 0
    for fq, (path, pkg, _src) in sorted(infos.items()):
        rel = os.path.relpath(path, JAVA_ROOT)
        expected = os.path.dirname(rel).replace(os.sep, ".")
        if pkg != expected:
            bad += 1
            err("package/dir", "%s\n        declares '%s' but lives in '%s'"
                % (os.path.relpath(path, ROOT), pkg, expected))
    print("   files checked: %d   mismatches: %d" % (len(infos), bad))


def check_internal_imports(infos):
    section("2. internal import resolution (com.saad.capvid.*)")
    declared = set(infos)
    # also collect nested types, e.g. CaptionOverlayView.CaptionStyleType
    nested = set()
    for fq, (_p, _pkg, src) in infos.items():
        outer = fq.rsplit(".", 1)[-1]
        for m in re.finditer(r"\benum\s+(\w+)|\bclass\s+(\w+)|\binterface\s+(\w+)", src):
            nested.add(fq.rsplit(".", 1)[0] + "." + outer + "." + (m.group(1) or m.group(2) or m.group(3)))
    unresolved = 0
    for fq, (path, _pkg, src) in sorted(infos.items()):
        for m in re.finditer(r"^\s*import\s+(?:static\s+)?(com\.saad\.capvid\.[\w.*]+)\s*;", src, re.M):
            imp = m.group(1)
            if imp.endswith(".*"):
                continue
            # com.saad.capvid.R is generated by aapt2 from res/, not a source file
            if imp == "com.saad.capvid.R":
                continue
            if imp in declared or imp in nested:
                continue
            unresolved += 1
            err("import", "%s\n        unresolved import: %s" % (os.path.relpath(path, ROOT), imp))
    print("   unresolved internal imports: %d" % unresolved)


# ---------------------------------------------------------------- 3 + 4 -----
def path_of(infos, fqcn):
    """File path of a declared top-level type, derived from its own package."""
    entry = infos.get(fqcn)
    if entry is None:
        raise KeyError("no such declared type: " + fqcn)
    return entry[0]


def src_of(infos, fqcn):
    return open(path_of(infos, fqcn), encoding="utf-8").read()


def enum_values(src, enum_name):
    m = re.search(r"enum\s+" + enum_name + r"\s*\{(.*?)\}", src, re.S)
    if not m:
        return None
    body = m.group(1)
    body = re.sub(r"//.*", "", body)
    return [v.strip() for v in body.split(",") if v.strip()]


def style_ids_from_catalog(src):
    return re.findall(r'style\(\s*"([A-Z0-9_]+)"', src)


def check_style_consistency(infos):
    section("3. style catalog <-> CaptionStyleType enum <-> StyleFontMap")
    cov = infos["com.saad.capvid.caption.CaptionOverlayView"][2]
    enum_vals = enum_values(cov, "CaptionStyleType")
    print("   CaptionStyleType values: %d" % len(enum_vals))

    cat_src = src_of(infos, "com.saad.capvid.style.CaptionStyleCatalog")
    cat_ids = style_ids_from_catalog(cat_src)
    print("   CaptionStyleCatalog entries: %d" % len(cat_ids))
    dupes = {i for i in cat_ids if cat_ids.count(i) > 1}
    if dupes:
        err("catalog", "duplicate catalog ids: %s" % sorted(dupes))

    missing_enum = [i for i in cat_ids if i not in enum_vals]
    orphan_enum = [e for e in enum_vals if e not in cat_ids]
    for i in missing_enum:
        err("catalog/enum", "catalog id '%s' has no CaptionStyleType -> TemplatePickerBottomSheet "
                           "will throw IllegalArgumentException when applied" % i)
    if orphan_enum:
        warn("catalog/enum", "enum values with no catalog entry (unreachable from picker): %s" % orphan_enum)

    # StyleFontMap no longer keeps its own table; it derives the asset from
    # CaptionStyleDefinition.fontAsset. So the contract to check is that every
    # enum value has a catalog entry carrying a font asset that exists on disk.
    catalog_fonts = dict(re.findall(
        r'style\("([A-Z0-9_]+)",\s*"[^"]*",\s*cats\(\w+\),\s*\n?\s*colors\([^)]*\),\s*"([^"]+)"',
        cat_src))
    fonts_dir_chk = os.path.join(ASSETS_ROOT, "fonts")
    missing = [e for e in enum_vals if e not in catalog_fonts]
    if missing:
        err("stylefontmap", "enum values with no catalog entry, so no font can be resolved "
                            "for them at export time: %s" % missing)
    bad_assets = [f for f in set(catalog_fonts.values())
                  if not os.path.exists(os.path.join(fonts_dir_chk, f))]
    for f in bad_assets:
        err("stylefontmap", "catalog names font asset '%s' which is not in assets/fonts" % f)
    print("   catalog font assets resolved: %d distinct, all present: %s"
          % (len(set(catalog_fonts.values())), not bad_assets))

    msaw_src = src_of(infos, "com.saad.capvid.style.renderer.ModernStyleAssWriter")
    modern_ids = re.findall(r'"([A-Z0-9_]+)"', msaw_src.split("MODERN_IDS")[1].split(";")[0])
    for i in modern_ids:
        if i not in enum_vals:
            err("modernasswriter", "ModernStyleAssWriter lists unknown style id '%s'" % i)
    print("   catalog ids missing from enum: %d | enum orphans: %d" % (len(missing_enum), len(orphan_enum)))
    return enum_vals


# ---------------------------------------------------------------- 5 + 11 ----
def check_fonts(infos):
    section("4/5. bundled fonts, references, and REAL ASS family names")
    fonts_dir = os.path.join(ASSETS_ROOT, "fonts")
    on_disk = sorted(os.listdir(fonts_dir)) if os.path.isdir(fonts_dir) else []
    print("   fonts in assets/fonts: %d" % len(on_disk))

    referenced = set()
    for _fq, (_p, _pkg, src) in infos.items():
        for f in on_disk:
            if f in src:
                referenced.add(f)

    fm_src = src_of(infos, "com.saad.capvid.font.FontManager")
    fm_files = re.findall(r'"([^"]+\.(?:ttf|otf|TTF|OTF))"', fm_src)
    for f in fm_files:
        if f not in on_disk:
            err("fontmanager", "FontManager.FONT_FILES lists '%s' which is NOT in assets/fonts -> copy fails" % f)
    for f in on_disk:
        if f not in fm_files:
            err("fontmanager", "assets/fonts/%s is not in FontManager.FONT_FILES -> never copied to fontsdir, "
                               "so libass cannot find it at export time" % f)

    # NOTE: a font that no template names is NOT dead weight - FontListAdapter
    # offers every FontManager.FONT_FILES entry as a user-selectable override.
    unreferenced = sorted(set(on_disk) - referenced)
    if unreferenced:
        print("   (not named by any template, but user-selectable in the Fonts tab: %s)"
              % ", ".join(unreferenced))

    # real family names
    try:
        from fontTools.ttLib import TTFont
    except ImportError:
        warn("font/family", "fonttools not installed - family-name check skipped")
        return {}
    real_family = {}
    print("   %-34s %-24s %s" % ("file", "real family (name ID 1)", "bold face?"))
    for f in on_disk:
        try:
            t = TTFont(os.path.join(fonts_dir, f), fontNumber=0, lazy=True)
            nm = t["name"]
            rec = nm.getName(1, 3, 1, 0x409) or nm.getName(1, 1, 0, 0)
            sub = nm.getName(2, 3, 1, 0x409) or nm.getName(2, 1, 0, 0)
            fam = str(rec) if rec else "?"
            real_family[f] = fam
            print("   %-34s %-24s %s" % (f, fam, sub))
            t.close()
        except Exception as e:
            err("font/parse", "assets/fonts/%s could not be parsed as a font: %s" % (f, e))

    # compare against StyleFontMap's claimed assFamilyName
    sfm_src = src_of(infos, "com.saad.capvid.font.StyleFontMap")
    pairs = re.findall(r'ASS_FAMILY_NAMES\.put\("([^"]+)",\s*"([^"]+)"\)', sfm_src)
    print("   --- StyleFontMap asset -> claimed ASS family vs real ---")
    for f in fm_files:
        if f not in [a for a, _c in pairs]:
            err("font/ass", "assets/fonts/%s has no entry in StyleFontMap.ASS_FAMILY_NAMES, so an "
                            "export using it would fall back to a filename-derived family libass "
                            "may not match" % f)
    for asset, claimed in pairs:
        if asset not in real_family:
            err("font/ass", "StyleFontMap references missing asset '%s'" % asset)
            continue
        real = real_family[asset]
        ok = real.lower() == claimed.lower()
        print("   %-34s claimed=%-22s real=%-22s %s" % (asset, claimed, real, "OK" if ok else "<-- MISMATCH"))
        if not ok:
            err("font/ass", "StyleFontMap claims ASS family '%s' for %s but the font's real family is '%s'; "
                            "libass will not match it and will fall back to its default face in the EXPORTED video"
                % (claimed, asset, real))
    return real_family


# ---------------------------------------------------------------- 6 + 7 -----
def collect_resources():
    res = {}
    for d in sorted(os.listdir(RES_ROOT)):
        base = d.split("-")[0]
        path = os.path.join(RES_ROOT, d)
        if base == "values":
            for f in os.listdir(path):
                if not f.endswith(".xml"):
                    continue
                tree = ET.parse(os.path.join(path, f))
                for el in tree.getroot():
                    if el.tag in ("string", "color", "dimen", "style", "bool", "integer", "string-array"):
                        res.setdefault(el.tag, set()).add(el.get("name"))
            continue
        if base in ("layout", "drawable", "mipmap", "anim", "menu", "xml", "raw"):
            for f in os.listdir(path):
                res.setdefault(base, set()).add(os.path.splitext(f)[0])
    return res


def check_resources(infos, res):
    section("6. R.* references resolve to real resources")
    kind_map = {"layout": "layout", "id": "id", "drawable": "drawable", "string": "string",
                "mipmap": "mipmap", "style": "style", "color": "color", "dimen": "dimen"}
    # ids come from @+id/ in layouts
    ids = set()
    for d in os.listdir(RES_ROOT):
        if not d.startswith("layout"):
            continue
        for f in os.listdir(os.path.join(RES_ROOT, d)):
            for m in re.finditer(r'@\+id/(\w+)', open(os.path.join(RES_ROOT, d, f), encoding="utf-8").read()):
                ids.add(m.group(1))
    available = {"id": ids}
    for k in kind_map:
        if k != "id":
            available[k] = res.get(k, set())

    bad = 0
    for fq, (path, _pkg, src) in sorted(infos.items()):
        # negative lookbehind so framework/library-qualified refs such as
        # android.R.drawable.x or com.google.android.material.R.id.y are not
        # mistaken for references to THIS module's generated R class
        for m in re.finditer(r"(?<![\w.])\bR\.(\w+)\.(\w+)", src):
            kind, name = m.group(1), m.group(2)
            if kind == "styleable":
                continue
            if kind not in kind_map:
                bad += 1
                err("resource", "%s references unknown R type R.%s.%s"
                    % (os.path.relpath(path, ROOT), kind, name))
                continue
            if name not in available[kind]:
                bad += 1
                err("resource", "%s references R.%s.%s which does not exist in res/"
                    % (os.path.relpath(path, ROOT), kind, name))
    print("   unresolved R.* references: %d" % bad)
    return ids


def check_findviewbyid(infos, ids):
    section("7. findViewById ids exist in the Activity's own layout")
    for fq, (path, _pkg, src) in sorted(infos.items()):
        if "findViewById" not in src:
            continue
        lay = re.search(r"setContentView\(R\.layout\.(\w+)\)", src)
        layout_name = lay.group(1) if lay else None
        used = set(re.findall(r"findViewById\(R\.id\.(\w+)\)", src))
        if layout_name is None:
            for u in sorted(used):
                if u not in ids:
                    err("layout", "%s uses R.id.%s which no layout declares"
                        % (os.path.relpath(path, ROOT), u))
            continue
        # ids reachable from this layout: its own + any <include>
        reachable = layout_ids(layout_name, set())
        for u in sorted(used):
            if u not in reachable:
                err("layout", "%s does findViewById(R.id.%s) but activity_%s.xml does not declare it"
                    % (os.path.relpath(path, ROOT), u, layout_name.replace("activity_", "")))


def layout_ids(name, seen):
    if name in seen:
        return set()
    seen.add(name)
    out = set()
    for d in os.listdir(RES_ROOT):
        if not d.startswith("layout"):
            continue
        p = os.path.join(RES_ROOT, d, name + ".xml")
        if os.path.exists(p):
            src = open(p, encoding="utf-8").read()
            out |= set(re.findall(r"@\+id/(\w+)", src))
            for inc in re.findall(r'<include[^>]*layout="@layout/(\w+)"', src):
                out |= layout_ids(inc, seen)
    return out


# ---------------------------------------------------------------- 8 ---------
def jni_mangle(cls, method):
    return "Java_" + cls.replace(".", "_").replace("$", "_00024") + "_" + method


def check_jni(infos):
    section("8. WhisperBridge native methods <-> native-lib.cpp symbols")
    bridge_src = infos["com.saad.capvid.whisper.WhisperBridge"][2]
    natives = re.findall(r"\bnative\s+([\w\[\]]+)\s+(\w+)\s*\(", bridge_src)
    cpp = open(os.path.join(CPP_ROOT, "native-lib.cpp"), encoding="utf-8").read()
    symbols = set(re.findall(r"JNICALL\s*\n?\s*(Java_[A-Za-z0-9_]+)", cpp)) | set(re.findall(r"(Java_[A-Za-z0-9_]+)\s*\(", cpp))
    bad = 0
    for _ret, name in natives:
        want = jni_mangle("com.saad.capvid.whisper.WhisperBridge", name)
        ok = want in symbols
        print("   %-22s -> %s  %s" % (name, want, "OK" if ok else "*** MISSING (UnsatisfiedLinkError at runtime) ***"))
        if not ok:
            bad += 1
            err("jni", "%s has no JNI implementation in native-lib.cpp -> UnsatisfiedLinkError" % name)
    extra = [s for s in symbols if not any(s == jni_mangle("com.saad.capvid.whisper.WhisperBridge", n) for _r, n in natives)]
    for e in sorted(extra):
        warn("jni", "native-lib.cpp defines %s with no matching Java native declaration (dead code)" % e)
    print("   missing JNI symbols: %d" % bad)


# ---------------------------------------------------------------- 9 + 10 ----
def check_manifest(infos):
    section("9. manifest activities exist")
    man = open(os.path.join(ROOT, "app/src/main/AndroidManifest.xml"), encoding="utf-8").read()
    pkg = "com.saad.capvid"
    for m in re.finditer(r'<activity\s+android:name="([^"]+)"', man):
        n = m.group(1)
        fq = n if "." in n and not n.startswith(".") else pkg + ("." + n[1:] if n.startswith(".") else "." + n)
        if fq not in infos:
            err("manifest", "manifest declares %s but no such class exists" % fq)
        else:
            print("   %s OK" % fq)


def submodule_paths():
    p = os.path.join(ROOT, ".gitmodules")
    if not os.path.exists(p):
        return set()
    return set(re.findall(r"^\s*path\s*=\s*(\S+)", open(p, encoding="utf-8").read(), re.M))


def check_cmake():
    section("10. CMakeLists paths exist")
    cm = open(os.path.join(CPP_ROOT, "CMakeLists.txt"), encoding="utf-8").read()
    for m in re.finditer(r"add_subdirectory\((\w+)", cm):
        p = os.path.join(CPP_ROOT, m.group(1))
        exists = os.path.isdir(p)
        print("   add_subdirectory(%s) -> %s" % (m.group(1), "present" if exists else "*** ABSENT (build blocker) ***"))
        if not exists:
            err("cmake", "add_subdirectory(%s) but app/src/main/cpp/%s is not in the repository" % (m.group(1), m.group(1)))
    subs = submodule_paths()
    for m in re.finditer(r"target_include_directories\([\w ]+PRIVATE\n?([\s\S]*?)\)", cm):
        for inc in re.findall(r"([\w/.-]+)\)?", m.group(1)):
            inc = inc.strip()
            if not inc or inc in ("PRIVATE", "PUBLIC"):
                continue
            p = os.path.join(CPP_ROOT, inc)
            if os.path.exists(p):
                continue
            # A path inside a declared git submodule is legitimately empty until
            # the developer runs `git submodule update --init --recursive`.
            inside_sub = any(("app/src/main/cpp/" + inc).startswith(sp + "/") or
                             ("app/src/main/cpp/" + inc) == sp for sp in subs)
            if inside_sub:
                print("   include '%s' is inside a submodule (populated by "
                      "`git submodule update --init`)" % inc)
            else:
                err("cmake", "target_include_directories refers to '%s' which does not exist" % inc)
    for m in re.finditer(r"add_library\(\w+\s+SHARED\s+([\s\S]*?)\)", cm):
        for srcfile in re.findall(r"([\w.-]+\.(?:cpp|c))", m.group(1)):
            if not os.path.exists(os.path.join(CPP_ROOT, srcfile)):
                err("cmake", "add_library lists source '%s' which does not exist" % srcfile)


def strip_java_literals(body):
    """Removes string/char literals and comments so brace counting is not fooled
    by e.g. a URL containing '//' or an escaped quote."""
    out = []
    i, n = 0, len(body)
    while i < n:
        c = body[i]
        if c in ('"', "'"):
            quote = c
            i += 1
            while i < n:
                if body[i] == "\\":
                    i += 2
                    continue
                if body[i] == quote:
                    i += 1
                    break
                i += 1
            out.append(quote * 2)
            continue
        if c == "/" and i + 1 < n and body[i + 1] == "/":
            while i < n and body[i] != "\n":
                i += 1
            continue
        if c == "/" and i + 1 < n and body[i + 1] == "*":
            i += 2
            while i + 1 < n and not (body[i] == "*" and body[i + 1] == "/"):
                i += 1
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def check_balance(infos):
    section("0. structural balance of every .java file")
    extra = []
    for root in ("app/src/test/java",):
        base = os.path.join(ROOT, root)
        for dirpath, _d, names in os.walk(base):
            for n in names:
                if n.endswith(".java"):
                    extra.append(os.path.join(dirpath, n))
    bad = 0
    for path in sorted(list(infos.values()) and [v[0] for v in infos.values()] + extra):
        code = strip_java_literals(open(path, encoding="utf-8").read())
        b = code.count("{") - code.count("}")
        pa = code.count("(") - code.count(")")
        br = code.count("[") - code.count("]")
        if b or pa or br:
            bad += 1
            err("balance", "%s  braces=%+d parens=%+d brackets=%+d"
                % (os.path.relpath(path, ROOT), b, pa, br))
    print("   files checked: %d   unbalanced: %d"
          % (len(infos) + len(extra), bad))


def main():
    files, infos = load_java()
    check_balance(infos)
    check_packages(files, infos)
    check_internal_imports(infos)
    check_style_consistency(infos)
    check_fonts(infos)
    res = collect_resources()
    check_resources(infos, res)
    ids = set()
    for d in os.listdir(RES_ROOT):
        if d.startswith("layout"):
            for f in os.listdir(os.path.join(RES_ROOT, d)):
                ids |= set(re.findall(r"@\+id/(\w+)", open(os.path.join(RES_ROOT, d, f), encoding="utf-8").read()))
    check_findviewbyid(infos, ids)
    check_jni(infos)
    check_manifest(infos)
    check_cmake()

    section("SUMMARY")
    for w in WARNINGS:
        print("  WARN  [%s] %s" % w)
    for e in ERRORS:
        print("  ERROR [%s] %s" % e)
    print("\n  errors: %d   warnings: %d" % (len(ERRORS), len(WARNINGS)))
    return 1 if ERRORS else 0


if __name__ == "__main__":
    sys.exit(main())
